import { AppEntry } from "./types";

export const DEFAULT_APPS: AppEntry[] = [
  {
    id: "youtube",
    label: "YouTube",
    kind: "web",
    url: "https://www.youtube.com/tv",
    fullscreen: true,
    icon: "/icons/youtube.svg",
    order: 1,
    enabled: true,
  },
  {
    id: "plex",
    label: "Plex",
    kind: "web",
    url: "https://app.plex.tv/desktop",
    fullscreen: true,
    icon: "/icons/plex.svg",
    order: 2,
    enabled: true,
  },
  {
    id: "twitch",
    label: "Twitch",
    kind: "web",
    url: "https://twitch.tv",
    fullscreen: true,
    icon: "/icons/twitch.svg",
    order: 3,
    enabled: true,
  },
  {
    id: "netflix",
    label: "Netflix",
    kind: "web",
    url: "https://www.netflix.com",
    fullscreen: true,
    icon: "/icons/netflix.svg",
    order: 4,
    enabled: true,
  },
  {
    id: "prime",
    label: "Prime",
    kind: "web",
    url: "https://www.primevideo.com",
    fullscreen: true,
    icon: "/icons/prime.svg",
    order: 5,
    enabled: true,
  },
  {
    id: "hulu",
    label: "Hulu",
    kind: "web",
    url: "https://www.hulu.com",
    fullscreen: true,
    icon: "/icons/hulu.svg",
    order: 6,
    enabled: true,
  },
  {
    id: "launch",
    label: "Launch",
    kind: "web",
    url: "https://launch.bmo.guru",
    fullscreen: true,
    icon: "/icons/launch.svg",
    order: 98,
    enabled: true,
  },
  {
    id: "player",
    label: "Play URL",
    kind: "player",
    url: "", // provided at launch time
    cmd: "mpv",
    args: ["--fullscreen", "--hwdec=auto"],
    icon: "/icons/play.svg",
    order: 99,
    enabled: true,
  },
];
